### ISSUE TITLE
Improve lookbook layout

### ISSUE THREAD

**Issue by nerdinand** [nerdinand/chorbasel-app#64]
Improve the layout of the lookbook pictures. They should all be displayed in the same size.
<img width="1319" alt="Screenshot 2024-12-11 at 17 28 39" src="https://github.com/user-attachments/assets/9ed1bbb6-ac4e-4e75-a43f-d481bc8239ab" />

**Comment by x-tropy** [comment]
The most important parts of pictures in Lookbook is the faces and the name tags members are holding. So if a picture is too long, we may clip the upper part of it; if a picture is too wide, then we display the center part of it.

Hopefully, this illustration may explain better:
![image](https://github.com/user-attachments/assets/9b25247b-08ad-4d35-95c4-7db65409175d)

**Comment by x-tropy** [comment]
![animated icon 6](https://github.com/user-attachments/assets/b17ad046-a4e9-4893-915a-29c6e4a8f1e2)

**Comment by x-tropy** [comment]
We may apply the "golden ratio: 1.618" here 😆

**Comment by nerdinand** [comment]
Exactly, perfect!
